from __future__ import annotations

import sys
from datetime import datetime
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

import yaml

from pulsedb_subset.pipeline.config import project_root, load_config
from pulsedb_subset.pipeline.io_mat import load_json


def _log(msg: str) -> None:
    print(f"[{datetime.now().strftime('%H:%M:%S')}] {msg}")


def main() -> int:
    _log("05_export_paper_artifacts: start")
    cfg = load_config()
    cfg.artifacts_dir.mkdir(parents=True, exist_ok=True)

    # Persist an explicit training config snapshot for reproducibility
    snapshot_path = cfg.artifacts_dir / "train_config.yaml"
    raw_cfg = yaml.safe_load((project_root() / "config.yaml").read_text(encoding="utf-8"))

    schema_path = cfg.artifacts_dir / "schema_map.json"
    schema = load_json(schema_path) if schema_path.exists() else {}
    _log(f"schema_map present={schema_path.exists()} subsets={len(schema) if schema else 0}")

    snapshot = {
        "date_note": "Generated by scripts/05_export_paper_artifacts.py",
        "config": raw_cfg,
        "schema_map_present": bool(schema),
        "schema_dataset_map": {k: v.get("dataset_map", {}) for k, v in (schema or {}).items()},
    }

    snapshot_path.write_text(yaml.safe_dump(snapshot, sort_keys=False, allow_unicode=True), encoding="utf-8")
    _log(f"wrote: {snapshot_path}")

    required = [
        cfg.artifacts_dir / "stats_by_subset.csv",
        cfg.artifacts_dir / "missingness_by_subset.csv",
        cfg.artifacts_dir / "qc_metrics.csv",
        cfg.artifacts_dir / "dropped_segments.csv",
        cfg.artifacts_dir / "subject_splits.yaml",
        cfg.artifacts_dir / "subject_overlap.csv",
        cfg.artifacts_dir / "split_stats_by_subset.csv",
        cfg.artifacts_dir / "scalers.json",
        snapshot_path,
    ]

    missing = [p for p in required if not p.exists()]
    if missing:
        print("[WARN] Missing some artifacts:")
        for p in missing:
            print(f"- {p}")
        _log("05_export_paper_artifacts: done (incomplete)")
        return 2

    print("Paper artifacts ready:")
    for p in required:
        print(f"- {p}")

    _log("05_export_paper_artifacts: done")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
